export const taskData = async () => [
  {
    id: 126,
    title: 'Garden Maintenance',
    date: new Date(2024, 4, 15),
    note: 'Trim the hedges and mow the lawn',
    isCompleted: false,
    houseId: 106,
    assigneeId: 101,
  },
  {
    id: 127,
    title: 'Paint the fence',
    date: new Date(2024, 4, 10),
    note: 'Use weather-resistant paint',
    isCompleted: true,
    houseId: 107,
    assigneeId: 102,
  },
  {
    id: 128,
    title: 'Fix the leaking tap',
    date: new Date(2024, 5, 5),
    note: null,
    isCompleted: true,
    houseId: 108,
    assigneeId: 103,
  },
  {
    id: 129,
    title: 'Organize the garage',
    date: new Date(2024, 5, 20),
    note: 'Sort items into labeled boxes',
    isCompleted: false,
    houseId: 109,
    assigneeId: 104,
  },
  {
    id: 130,
    title: 'Replace kitchen light',
    date: new Date(2024, 5, 25),
    note: 'Buy energy-efficient LED bulb',
    isCompleted: false,
    houseId: 110,
    assigneeId: 105,
  },
];
