-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "itemName" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "House" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "Rule" ALTER COLUMN "text" SET DATA TYPE VARCHAR(200);

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "title" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "note" SET DATA TYPE VARCHAR(200);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(100);
