version: "3.8"
services:
  postgres:
    image: postgres:latest
    env_file: .env
    container_name: 'fairy-share-db'
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
