name: Client Lint and Format

on:
  push:
    paths:
      - client/**
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10.0]

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm
        run: npm ci

      - name: Lint code
        run: npm run lint:fix

      - name: Format code
        run: npm run format

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply lint format changes
